import DesignForm from '@/components/DesignForm'

export default function Home() {
  return (
    <main className="relative z-10 min-h-screen px-4 pb-24 pt-16 sm:px-6">
      <div className="mx-auto max-w-2xl">

        {/* ── Header ─────────────────────────────── */}
        <header className="mb-14 text-center">
          {/* Decorative rule */}
          <div className="mx-auto mb-6 flex items-center justify-center gap-3 opacity-50">
            <div className="h-px w-16 bg-gradient-to-r from-transparent to-blush-200" />
            <Gem />
            <div className="h-px w-16 bg-gradient-to-l from-transparent to-blush-200" />
          </div>

          <p className="mb-2 font-sans text-xs font-semibold uppercase tracking-[0.22em] text-mauve-400">
            AI Nail Design Studio
          </p>
          <h1 className="font-serif text-4xl font-bold leading-tight text-mauve-700 sm:text-5xl">
            Dream Nails
          </h1>
          <p className="mt-4 font-sans text-sm leading-relaxed text-gray-400 sm:text-base">
            Describe your vision — shape, length, colours, and style.
            <br className="hidden sm:block" />
            Receive two photorealistic designs in seconds.
          </p>
        </header>

        {/* ── Card ───────────────────────────────── */}
        <div className="rounded-3xl border border-pearl-200 bg-white/80 p-6 shadow-sm shadow-pearl-200 backdrop-blur-sm sm:p-10">
          <DesignForm />
        </div>

        {/* ── Footer ─────────────────────────────── */}
        <footer className="mt-12 text-center">
          <p className="text-xs text-gray-300">
            Images generated by OpenAI DALL&middot;E 3 &nbsp;&bull;&nbsp; Powered by n8n
          </p>
        </footer>

      </div>
    </main>
  )
}

function Gem() {
  return (
    <svg
      width="10"
      height="10"
      viewBox="0 0 10 10"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M5 0.5L9.5 4L5 9.5L0.5 4L5 0.5Z"
        fill="#F9B8D0"
        stroke="#C4768A"
        strokeWidth="0.5"
      />
    </svg>
  )
}
